include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    - '**.g.dart'

linter:
  rules:
    unawaited_futures: true
    require_trailing_commas: false
    depend_on_referenced_packages: false
    avoid_redundant_argument_values: false
    type_annotate_public_apis: true
