name: pd_app
description: Digital Patient Directive

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  arrow_path: ^3.0.0
  checkbox_formfield: ^0.2.0
  expandable: ^5.0.1
  file_picker: ^5.2.5
  file_saver: ^0.1.1
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.5.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_svg: 1.1.0
  get_it: 7.2.0
  go_router: 6.0.7
  intl: 0.17.0
  json_annotation: ^4.8.0
  logger: 1.1.0
  path_provider: ^2.0.12
  pdf: ^3.9.0
  pdfx: ^2.3.0
  printing: ^5.10.1
  provider: 6.0.2
  responsive_sizer: ^3.0.8
  retry: ^3.1.0
  rxdart: ^0.27.3
  share_plus: ^6.3.1
  stack_trace: 1.11.0

dev_dependencies:
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  http: 0.13.5
  json_serializable: ^6.6.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  lint: ^2.0.1
  mockito: 5.3.2

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/markdown/
    - assets/cms/
