// Mocks generated by Mockito 5.3.2 from annotations
// in pd_app/test/main_app/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:logger/logger.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pd_app/general/dynamic_content/components/content_definition.dart' as _i7;
import 'package:pd_app/general/dynamic_content/loading/cms_config.dart' as _i2;
import 'package:pd_app/general/dynamic_content/loading/cms_loader.dart' as _i4;
import 'package:pd_app/general/dynamic_content/loading/json_serializable.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCmsConfig_0 extends _i1.SmartFake implements _i2.CmsConfig {
  _FakeCmsConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_1 extends _i1.SmartFake implements _i3.Logger {
  _FakeLogger_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCmsLoadingResult_2<T> extends _i1.SmartFake implements _i4.CmsLoadingResult<T> {
  _FakeCmsLoadingResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CMSLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockCMSLoader extends _i1.Mock implements _i4.CMSLoader {
  MockCMSLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CmsConfig get cmsConfig => (super.noSuchMethod(
        Invocation.getter(#cmsConfig),
        returnValue: _FakeCmsConfig_0(
          this,
          Invocation.getter(#cmsConfig),
        ),
      ) as _i2.CmsConfig);

  @override
  String get apiToken => (super.noSuchMethod(
        Invocation.getter(#apiToken),
        returnValue: '',
      ) as String);

  @override
  _i3.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_1(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i3.Logger);

  @override
  _i5.Future<_i4.CmsLoadingResult<T>> loadEntitiesFromCMS<T extends _i6.SerializableAsset>({
    required String? locale,
    required _i7.ContentDefinition<T>? contentDefinition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEntitiesFromCMS,
          [],
          {
            #locale: locale,
            #contentDefinition: contentDefinition,
          },
        ),
        returnValue: _i5.Future<_i4.CmsLoadingResult<T>>.value(_FakeCmsLoadingResult_2<T>(
          this,
          Invocation.method(
            #loadEntitiesFromCMS,
            [],
            {
              #locale: locale,
              #contentDefinition: contentDefinition,
            },
          ),
        )),
      ) as _i5.Future<_i4.CmsLoadingResult<T>>);

  @override
  _i5.Future<_i8.Uint8List> downloadMediaUri(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #downloadMediaUri,
          [uri],
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);
}
