mixin PlaceholderText {
  static String placeholderText = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacus felis, auctor in risus vel, tristique iaculis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin egestas eget libero nec posuere. Morbi id leo auctor, vulputate felis hendrerit, euismod felis. Duis mattis efficitur justo sollicitudin ullamcorper. Quisque fringilla, mauris a facilisis sodales, nulla tellus consequat turpis, ut volutpat urna metus ut ante. Morbi convallis magna cursus nibh sodales volutpat. Nullam quis tempus orci. Vestibulum vel neque quis lectus varius sodales. Proin sit amet tincidunt nulla, non mattis dolor. Donec id fermentum mi, nec rhoncus est.

Curabitur varius lorem orci, congue cursus metus tristique placerat. Praesent vitae sem sed erat accumsan interdum. Nunc vel ante ut nibh imperdiet ultricies sit amet vel nulla. Aliquam et pellentesque mi, eu elementum orci. Curabitur eu tortor ut dui sagittis blandit sed eget dolor. Ut bibendum laoreet sapien id venenatis. Duis tincidunt metus a purus facilisis, a ultricies elit suscipit. Cras molestie risus vel diam interdum, ac luctus erat aliquet. Aenean tincidunt mi nec nulla condimentum ornare. Duis felis magna, eleifend eget turpis quis, rutrum vehicula erat. Integer ut lacus tincidunt, molestie ipsum eu, bibendum felis. Ut lacinia ligula nunc, non eleifend nisl vehicula non.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent vitae orci a libero placerat volutpat vitae ut purus. In maximus varius libero, non euismod arcu lobortis sed. Mauris sit amet libero felis. Fusce id nisl elementum, tempor justo nec, dictum sem. In non tristique massa. Integer rutrum lacus at risus varius hendrerit. Praesent vitae molestie risus. Praesent vitae lobortis ipsum, ut auctor nulla. Quisque malesuada ligula nec eros sodales tincidunt. Sed tellus risus, pellentesque at consectetur quis, scelerisque eget lorem. Aliquam scelerisque vulputate risus quis gravida. Vivamus enim leo, gravida vitae velit sed, laoreet gravida felis. Aliquam purus lacus, iaculis eu urna ac, euismod feugiat purus. Morbi condimentum sodales mauris non interdum. Maecenas sed dignissim purus.

Donec viverra auctor orci a facilisis. Vivamus suscipit, neque a pulvinar aliquet, libero odio maximus libero, sit amet congue odio sapien a orci. Integer nec rutrum augue, sed maximus dui. Fusce a dolor in tortor luctus rutrum vitae quis libero. Etiam accumsan at arcu ut tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed interdum purus id lectus lobortis, nec maximus magna pellentesque. In tempor neque augue, congue tempus eros volutpat ut. Praesent eget nibh libero. Nam scelerisque nibh quis iaculis accumsan. Fusce nec orci interdum ex imperdiet dignissim. Nullam efficitur, neque sit amet sodales laoreet, lacus est pulvinar enim, quis blandit neque nisl sit amet ligula. Nullam nulla massa, posuere in molestie ornare, ornare faucibus enim.

Maecenas quis libero dignissim, faucibus sapien vitae, accumsan lorem. Proin tortor sem, bibendum at risus vitae, varius porta turpis. Vestibulum quam libero, eleifend non risus eget, commodo dapibus massa. Donec semper erat et tortor rutrum, vitae laoreet orci ornare. Sed et ornare nunc. Nullam porta ornare ultricies. Ut aliquet tortor sed ante fermentum hendrerit. Suspendisse potenti.

Quisque sed porta sapien. Curabitur vehicula ullamcorper purus at consequat. Morbi euismod justo nisl, lobortis tempus ex ultrices id. Aenean ac ullamcorper tellus, quis porttitor purus. Aenean vitae turpis vulputate, interdum justo blandit, tincidunt nulla. Duis mattis sagittis tortor, ac interdum sem suscipit ut. Sed congue pretium commodo. Fusce aliquam nunc in neque hendrerit, a malesuada enim ullamcorper. In eget odio non nisi eleifend condimentum sit amet in urna. Nulla a varius velit. Sed et tincidunt mi. Vivamus congue dictum leo eget pretium.

Vestibulum ullamcorper massa at scelerisque pharetra. Duis vitae interdum massa, ac scelerisque ligula. Vivamus quam elit, laoreet vitae nulla vitae, facilisis congue est. Donec et varius dolor. Nullam in neque quis arcu hendrerit rhoncus. Integer rhoncus eros ac diam aliquam, a iaculis ex condimentum. Mauris facilisis, tortor non aliquam semper, metus tortor lobortis velit, a tristique quam lectus eget dolor. Phasellus id diam leo. Cras vitae leo vel massa fermentum laoreet a in turpis. Aliquam erat volutpat. Suspendisse viverra lorem risus, sit amet euismod dolor volutpat ut. Phasellus sit amet posuere lacus, eget commodo mauris. Sed nulla purus, egestas sit amet risus ac, ullamcorper blandit enim.

Etiam scelerisque, est fermentum euismod scelerisque, elit diam pellentesque massa, eu consequat augue sapien quis nibh. Praesent rutrum elit a interdum auctor. In tempus dui tristique, pharetra nunc quis, sagittis lacus. Maecenas et nunc id orci accumsan sollicitudin dapibus porta tortor. Sed posuere, erat fringilla placerat condimentum, nunc felis commodo nibh, vel consectetur diam metus auctor orci. In at sodales augue, a rhoncus nisi. Phasellus nec ipsum aliquam mauris ornare vulputate eu eget ante. Aenean mauris odio, scelerisque eget leo ac, sagittis ornare ipsum. Aliquam erat volutpat. Aenean aliquam arcu nec dolor lobortis feugiat. Aliquam rhoncus ligula eget lacus gravida gravida. Mauris eu cursus odio. Donec ac ullamcorper lorem, non mollis enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In aliquam ex mauris, nec dapibus mauris hendrerit sit amet.

Vivamus nec diam ex. Etiam tincidunt orci orci, at dignissim neque finibus vitae. Nunc congue odio sit amet sem auctor congue. Suspendisse tincidunt purus quis risus aliquam, ultrices cursus lacus ornare. Praesent nec arcu maximus, vulputate augue eget, ultrices leo. Aenean eu pharetra ipsum, vitae tincidunt elit. Phasellus libero odio, ornare et sodales at, suscipit finibus massa. Aliquam ultrices lectus vitae libero ultricies, iaculis interdum ex vehicula. Mauris vestibulum augue posuere est posuere aliquam. Pellentesque vitae accumsan quam. Donec egestas, ante at aliquet porta, dui massa egestas mi, sit amet efficitur dolor diam eu justo. Proin quam justo, viverra ac purus id, sagittis egestas mi. Suspendisse potenti. Donec laoreet ante metus, ac maximus diam facilisis malesuada. Morbi dapibus libero nec dui hendrerit, sit amet ultrices velit aliquet.

Donec id quam quis ante pharetra consequat. Fusce cursus euismod quam, nec commodo ex. Suspendisse eu enim non quam malesuada lacinia in vel enim. Nunc viverra feugiat orci, a tempor sapien ornare vitae. Fusce consequat tellus massa, ut molestie massa posuere vitae. Suspendisse nec elit arcu. Nunc ut aliquam nibh. Suspendisse id nulla arcu. Suspendisse tristique nibh sed convallis laoreet.

Etiam blandit pulvinar imperdiet. Sed dapibus vestibulum pulvinar. Suspendisse potenti. Nunc eu eros nec mauris varius rutrum. Nulla facilisi. Aliquam non lectus tortor. Vivamus bibendum, leo vitae tempus iaculis, neque arcu sodales lorem, quis mattis dolor justo in augue. Suspendisse imperdiet augue vel ipsum congue, a viverra sem eleifend. Sed rutrum risus id convallis semper. Ut ornare ac augue id accumsan. In et nibh eget leo aliquam tempus eget eu justo. Donec pulvinar vitae ipsum at lacinia. Nam efficitur ipsum orci, et egestas mauris aliquet ut.

Etiam euismod id purus ut pellentesque. In sed posuere nulla, ac imperdiet turpis. Aliquam tincidunt dapibus diam, sed tempus elit porta in. Mauris tempus nisi magna, a ullamcorper eros tincidunt non. Etiam lacinia venenatis ante non cursus. Fusce dignissim commodo dui, non semper eros rhoncus sed. Aenean rutrum nisi metus, eu sodales libero vestibulum eu. Integer aliquam sapien ut odio mollis tristique. Aenean pellentesque vestibulum sapien eu consectetur. Nulla molestie euismod ex, id viverra justo fermentum eget. Vestibulum consectetur a nisi ac iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam et elit hendrerit, accumsan enim ac, interdum ligula. Suspendisse ullamcorper, augue a cursus aliquet, est ligula hendrerit libero, eget pulvinar ex nibh ac orci.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam luctus tincidunt ante, sit amet ornare sapien scelerisque a. Donec dui nisl, maximus non lacus eget, fermentum eleifend velit. Aenean convallis interdum tristique. In tempor, ex sed auctor viverra, enim urna suscipit turpis, quis fermentum mauris sapien ac mauris. Curabitur rhoncus tellus et lorem dignissim, eu rhoncus risus congue. Quisque ac felis nisl. Curabitur placerat, justo ut blandit euismod, nisi orci egestas orci, et varius dolor turpis nec nibh. Maecenas ornare augue sed risus pulvinar, vel posuere quam laoreet. Vestibulum est enim, congue et mattis ac, accumsan vel libero. Vivamus viverra nulla non pellentesque congue.

Donec eget dolor quis odio posuere sodales. Suspendisse aliquam ornare eros, bibendum iaculis dui finibus ac. Aenean faucibus purus at lorem laoreet, consectetur ornare lacus ullamcorper. Fusce sit amet enim leo. Sed id tristique sem. Morbi sit amet interdum augue. Cras nulla justo, gravida in nunc ac, suscipit cursus risus. Aliquam eget metus libero. Fusce nulla mauris, auctor quis porta eget, luctus a dolor. Nam posuere ultricies ex, vel tincidunt augue efficitur et.

Nunc egestas a velit nec malesuada. In ac est ex. Ut finibus iaculis est id volutpat. Integer pharetra facilisis nisl, at iaculis massa lacinia quis. Aenean eu orci eget eros condimentum facilisis sagittis non urna. Mauris sagittis tellus mattis enim sodales, ut fringilla quam ullamcorper. Morbi at congue neque. Duis viverra congue mauris, at posuere elit tristique et. Proin id malesuada arcu. Duis bibendum erat eu risus volutpat lacinia in id velit. Ut pulvinar lorem at molestie condimentum. Vivamus quis urna eu sem dictum sodales. Nulla ornare consectetur interdum. In rutrum eros congue, pharetra sem ut, dapibus nisi.

Nullam tempor non elit ut vulputate. In tincidunt euismod rutrum. Fusce at nunc non nulla rhoncus finibus. Praesent rutrum id ipsum non mattis. Suspendisse ligula velit, posuere nec fermentum quis, vulputate ut eros. Praesent non leo volutpat, pellentesque velit vel, efficitur quam. Vestibulum molestie dictum leo a porta. Integer sagittis consequat dolor, nec vulputate arcu posuere vitae. Morbi varius diam dui, id sollicitudin enim sollicitudin vitae. Integer gravida neque lectus, bibendum convallis elit maximus at. Cras purus diam, vulputate vel dolor quis, placerat scelerisque urna. In scelerisque lacinia facilisis. Vestibulum convallis, augue sit amet iaculis molestie, mauris nibh sollicitudin dolor, sed tincidunt metus diam sit amet enim. Fusce bibendum sodales magna eget porttitor. Vivamus id neque sed ligula auctor pretium.

Donec tortor sem, cursus sit amet sagittis at, lacinia et orci. Aenean eu enim nec lorem tempus fringilla sed sit amet nulla. Pellentesque rhoncus ipsum at dolor fringilla feugiat. Nulla facilisi. Sed id pellentesque tortor. In vitae turpis ut metus consequat sollicitudin. Praesent pellentesque massa tortor, ut dapibus nisi luctus porta. Sed felis leo, auctor eu luctus a, blandit non nunc. Aliquam consectetur eleifend tincidunt. Pellentesque consequat rutrum augue, non blandit augue porta vel. Maecenas interdum faucibus dolor, non tempor sem varius vitae.

Etiam in suscipit sem. Suspendisse sed dui vitae augue porta feugiat. Nam maximus pellentesque dui ut condimentum. Morbi mi dui, eleifend suscipit nisl sit amet, ornare iaculis erat. Duis sollicitudin lectus metus, sit amet lobortis mi facilisis eu. Vivamus rutrum lorem eros. Pellentesque ornare sed sem eget vestibulum. Sed a purus consequat, iaculis ante nec, commodo felis. Maecenas vel velit felis. Morbi eu tempus tellus. Donec sapien eros, posuere nec feugiat et, dapibus sagittis magna. Nulla mollis risus sem, et suscipit lacus eleifend non. Donec ullamcorper pretium vehicula. Aliquam a urna quis dolor placerat mattis in vel diam. Sed volutpat eu tellus ac porta.

Nulla congue rhoncus tellus, eu dictum diam scelerisque facilisis. Fusce ac efficitur neque. Sed pulvinar condimentum odio, in interdum ex facilisis nec. Fusce pretium feugiat aliquet. Phasellus id lacus ut nulla sollicitudin euismod. Proin non nulla vel quam iaculis volutpat a a lorem. Praesent lobortis velit enim, non sodales ante pellentesque in.

Nullam venenatis metus sed nisi blandit, sed ultricies dolor luctus. Donec a orci nisl. Cras augue tortor, pharetra in consequat id, pharetra eu risus. Ut placerat, elit id efficitur fermentum, mauris felis fermentum urna, ac viverra felis elit a lorem. In sed dui in purus iaculis semper a at nibh. Nullam maximus, dui ac congue consequat, mauris velit semper dui, at pharetra ligula elit eget nisi. Quisque hendrerit sed lectus et posuere. Aliquam eget convallis arcu, eu consequat ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. In congue ac neque non lacinia. Praesent porta at tortor vel varius. Mauris lacinia ultrices lacinia.

Curabitur est libero, ornare sit amet ex id, cursus rutrum lectus. Vivamus porta pellentesque purus, in mollis eros venenatis at. Nunc luctus et metus eget venenatis. Nullam aliquet non lectus sed eleifend. Nulla sem lacus, tempus eu interdum sit amet, molestie eu erat. Suspendisse id commodo justo. Etiam ornare orci id lectus scelerisque facilisis. Vivamus ut congue orci. Duis mattis massa nibh, fermentum vestibulum sem efficitur eu.

Vivamus vel sem pellentesque, blandit sapien id, elementum lacus. Mauris tempus imperdiet iaculis. Nullam a urna in mi pellentesque condimentum. Proin sem lectus, aliquam pharetra neque in, tristique elementum nibh. Fusce eleifend sapien et odio sollicitudin, non sagittis sapien sagittis. Praesent porttitor sodales tristique. Vivamus tristique est eget tincidunt condimentum. Maecenas facilisis dui eget leo sollicitudin interdum. Vivamus posuere, metus non fermentum maximus, nisi mi semper risus, at hendrerit erat dolor vel velit. Vivamus ac augue at nulla ornare semper sed non dolor. Vivamus at erat orci. Phasellus mauris ligula, sodales quis nunc quis, consectetur faucibus tortor.

Nullam eros risus, elementum et laoreet eu, lobortis ac mi. Duis at tortor a est aliquet auctor non a odio. Aliquam ut pharetra dui. Mauris luctus posuere lacus sit amet aliquet. Aliquam erat volutpat. Sed feugiat justo sed velit facilisis condimentum. Nullam ut blandit elit. In fermentum mollis est sit amet mattis. Integer at sapien magna. Donec eu lacus a dui maximus aliquam ut ut libero. Ut pretium urna tempor purus cursus mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum, purus at tempus ultrices, nibh purus volutpat ex, sed accumsan tellus lorem at leo. Vestibulum ac elit luctus, varius turpis vitae, pellentesque ante.

Praesent congue est et molestie fringilla. Nunc sit amet eros posuere, sodales ligula nec, tempor tellus. Nam finibus ipsum nec nisl sodales euismod. Sed purus leo, sagittis in mauris nec, vulputate mollis massa. Curabitur a vestibulum leo, at tincidunt ligula. Integer et diam eu justo facilisis tempus sit amet sed mi. Donec blandit ligula mauris. Proin lectus leo, aliquet a eleifend at, consectetur sit amet magna. Nunc a ex in mauris semper faucibus. Donec a venenatis diam. Sed venenatis sem enim, a vulputate massa congue sit amet. Mauris laoreet gravida orci in mollis. Cras efficitur ipsum purus, ac condimentum turpis tempus ut. Ut in odio et ex porta luctus. Curabitur nec dui et tellus mollis placerat. Phasellus semper odio vitae nulla molestie convallis.

Maecenas feugiat mi enim, eu viverra diam consectetur ac. Phasellus rutrum suscipit dui et egestas. Praesent vehicula massa laoreet ullamcorper blandit. Aenean elementum odio nibh, a tristique eros semper vel. Quisque quis dictum nisl, ac elementum turpis. Ut ultrices sollicitudin ligula, a sodales odio convallis non. Praesent ipsum odio, sagittis accumsan neque sed, vulputate ullamcorper felis. Pellentesque eleifend semper lectus, cursus feugiat est. Donec mollis, ante ut suscipit commodo, est arcu consequat mi, ut pharetra dolor lectus congue est. Integer dapibus nisi vel venenatis pulvinar. Aliquam erat volutpat. Sed eu lorem eu felis ornare auctor ac a nibh. Fusce tincidunt iaculis tincidunt. Aliquam rutrum velit quis risus dignissim, eu posuere tellus placerat.

Suspendisse potenti. Mauris malesuada scelerisque luctus. Cras varius blandit dui, eu tempor dolor vestibulum quis. Etiam vel tellus sit amet arcu dictum viverra nec eget libero. Donec luctus facilisis erat, id laoreet magna cursus ac. Curabitur pharetra odio augue, vel tempor metus semper sed. Praesent vehicula posuere eros, vitae faucibus dui tempor et. Curabitur hendrerit commodo massa, vel dapibus magna sodales in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In congue ligula lacus, posuere pretium dui imperdiet ut.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat tempor tortor a varius. Vestibulum condimentum volutpat orci, pellentesque ultricies tortor molestie eu. Pellentesque mattis, nisi eu condimentum consectetur, ligula risus varius odio, eget tempus erat mauris sed tortor. Phasellus vitae tincidunt sem, ac porttitor tellus. Praesent enim orci, venenatis at massa vitae, rhoncus porttitor sapien. Donec tempus justo urna, quis suscipit neque malesuada sed. Curabitur eleifend velit sed velit bibendum convallis. Maecenas nec feugiat lorem. Nam tincidunt lacus eu vehicula congue.

Proin at gravida est, blandit condimentum quam. Cras quis commodo odio. Pellentesque volutpat ex est, vitae placerat tellus convallis et. Ut gravida fringilla libero, bibendum consectetur augue congue at. Vivamus ultrices mollis orci, eget feugiat mauris fermentum eget. Sed aliquam ligula at tempor faucibus. Aliquam volutpat tortor et magna posuere dapibus. Praesent sagittis elit eros, in dapibus nisl faucibus vel. Mauris augue nibh, rutrum id rutrum in, volutpat eu nunc. Sed pellentesque nulla eget fermentum viverra.

Donec erat enim, mattis sed magna ut, lobortis ornare nisl. Integer rhoncus efficitur nunc, a mollis dolor molestie at. Phasellus et pulvinar mauris, at ultrices risus. Proin nec magna felis. Etiam rutrum est eu nunc euismod, ac placerat augue efficitur. Vestibulum malesuada nulla volutpat nulla blandit dignissim. Morbi maximus, neque ac rhoncus feugiat, magna lorem pretium odio, a pulvinar ipsum arcu et sem. Ut sit amet quam condimentum, luctus purus eget, efficitur ligula. Nulla efficitur leo quis varius fermentum. Aliquam sit amet tellus accumsan, tempor neque quis, vehicula augue. Curabitur vulputate auctor nunc vitae hendrerit. Nullam sed orci mollis, porttitor est sed, pretium lectus.

Ut tellus justo, condimentum vitae malesuada et, gravida dictum magna. Ut dignissim facilisis eros, eu varius nunc consectetur in. In dictum turpis nec commodo commodo. Nullam in nisl turpis. Ut a lacus sapien. Praesent dapibus nibh ultrices orci blandit aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In sodales vitae nunc porta semper. Nullam mollis molestie lacus, eu semper diam lobortis et. Proin efficitur vitae mauris sed rhoncus. Cras pretium, diam ut finibus imperdiet, lacus nisi elementum mi, a tincidunt libero nulla a augue. Donec sodales sapien nec mauris interdum, eget efficitur leo rutrum. Pellentesque feugiat metus urna, non commodo ligula finibus eu. Duis sodales arcu ante, nec ornare enim auctor a. Duis at consectetur nulla, eu sollicitudin metus. Phasellus molestie, nunc vitae feugiat pretium, ipsum neque malesuada quam, eget rhoncus orci enim finibus risus.
 ''';
}
